### ISSUE TITLE
zodb_load_count and zodb_store_count as Counter

### ISSUE THREAD

**Issue by Nimo-19** [collective/collective.prometheus#4]
Hi, 

I'm struggling a bit to understand why **zodb_load_count** and **zodb_store_count** are defined as **Counters**.
I think understand that the underlying values are _monotonically increasing_.
But the data send to Prometheus is just the data of the last 15s. So this values can _arbitrarily go up or down_. So they should be **Gauges**, right?!

Am I missing something?

**Comment by skurfer** [comment]
I think you might be right, but I don’t want to just blindly push out the fix. Do you know how Prometheus will react to this change? Will it just automatically accept the new type, or will some intervention be required on the Prometheus side?
