### ISSUE TITLE
Metrics /zope_connection_[0-9]+.*/ are misnamed.

### ISSUE THREAD

**Issue by Rudd-O** [collective/collective.prometheus#8]
Understandable given that this is a direct port from the Munin metric.

In Prometheus, the name of the metric should not change with a numeric value.  The numeric value should, instead, be embedded as a label (perhaps `thread` fits in this case).

Thanks in advance -- I will see if I can come up with an easy fix.

**Comment by Rudd-O** [comment]
OK that was quick:

https://github.com/collective/collective.prometheus/pull/9/files

**Comment by cdw9** [comment]
PR released in version 1.6.1
